services:
  ps:
    image: ghcr.io/jeffpeng3/ppproxy:latest
    init: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp:/dev/ppp
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Asia/Taipei
      - RUST_LOG=${RUST_LOG:-info}

      - PPPOE_USERNAME=${PPPOE_USERNAME}
      - PPPOE_PASSWORD=${PPPOE_PASSWORD}
      - PPPOE_SESSION_COUNT=${PPPOE_SESSION_COUNT:-1}

      - IP_ROTATION_TIME=${IP_ROTATION_TIME}
      - IP_ROTATION_WAIT_SECONDS=${IP_ROTATION_WAIT_SECONDS}

      - PROXY_VERBOSE=${PROXY_VERBOSE:-1}

      - GATEWAY=${GATEWAY}

    env_file:
      - .env
    dns:
      - 1.1.1.1
    networks:
      pppoe_net: 
        ipv4_address: 1.2.3.4
networks:
  pppoe_net:
    driver: macvlan
    driver_opts:
      parent: eno1
