services:
  ps:
    image: ghcr.io/jeffpeng3/pppoe-socks:latest
    init: true
    cap_add:
      - NET_ADMIN
    networks:
      pppoe_net: null
    devices:
      - /dev/ppp:/dev/ppp
    stdin_open: true
    tty: true
    environment:
      - PPPOE_USER=${PPPOE_USER}
      - PPPOE_PASSWORD=${PPPOE_PASSWORD}
    env_file:
      - .env
networks:
  pppoe_net:
    driver: macvlan
    driver_opts:
      parent: eno1
